# Required START
substitutions:
  variant: "eu" # The only needed configuration
  component_link: github://kvj/hass_NSPanel_NG@0.1.2 # Most up-to-date
packages:
  device_base: github://kvj/hass_NSPanel_NG/nspanel_ng.yaml@0.1.2 # Most up-to-date
# Required END

esphome:
  name: "nspanel-ng-my-device"
  friendly_name: "NSPanel NG My Device"

wifi: # Configure as you'd like
  ssid: Change me

logger: # Configure as you'd like
